'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class client_account_registration

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''BtnDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDashboard As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnUpdateProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnUpdateProfile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLogout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''EmployeeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmployeeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LoginTimestamp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginTimestamp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtFirstName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckFirstName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtMiddleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtMiddleName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtLastName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckLastName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtCustomerIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCustomerIC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckCustomerIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckCustomerIC As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RevCustomerIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RevCustomerIC As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''TxtDateOfBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtDateOfBirth As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckDateOfBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckDateOfBirth As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RvDateOfBirth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RvDateOfBirth As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''RblGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RblGender As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''CheckGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckGender As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtContactNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''checkContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents checkContactNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RevContactNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RevContactNo As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''TxtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RevEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RevEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''TxtStreetAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtStreetAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckStreetAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckStreetAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtPostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtPostcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckPostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckPostcode As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RevPostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RevPostcode As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''RvPostcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RvPostcode As Global.System.Web.UI.WebControls.RangeValidator

    '''<summary>
    '''DdlState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlState As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CheckState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckState As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''LblAccNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblAccNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DdlAccType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlAccType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CheckDdlAccType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckDdlAccType As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TxtOpenDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtOpenDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxtInitialDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtInitialDeposit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckTxtInitialDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckTxtInitialDeposit As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CvTxtInitialDeposit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CvTxtInitialDeposit As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''BtnConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConfirm As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCancel As Global.System.Web.UI.WebControls.Button
End Class
