'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class fund_transfer

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''BtnAccOverview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAccOverview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnFundTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnFundTransfer As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnBillPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnBillPayment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnUpdateProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnUpdateProfile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnContactUs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnContactUs As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLogout As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''CustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LoginTimestamp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginTimestamp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TxtToAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtToAccount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckTxtToAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckTxtToAccount As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''DdlUserAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlUserAccount As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CheckDdlUserAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckDdlUserAccount As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''SqlDataSource1_customer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1_customer As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''TransferAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransferAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckTransferAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckTransferAmount As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''TransferDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransferDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CheckTransferDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckTransferDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''CvTransferDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CvTransferDate As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''TxtTransDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxtTransDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNext As Global.System.Web.UI.WebControls.Button
End Class
